### ISSUE TITLE
How to implement multistate grammar, or namespaces

### ISSUE THREAD

**Issue by pauljura** [phplrt/phplrt#25]
Hi,

I'm trying to migrate an old project from `hoa/compiler` to this. The project was for reading mustache-like input. I was using namespaces defined like this:
```
%token open_brace {{ -> sub
%token sub:close_brace }} -> default
```

I see you support a multistate lexer: https://phplrt.org/docs/lexer/multistate which suggests that what I want should be possible, but I'm having trouble putting everything together.

I'm starting from the guide here https://phplrt.org/docs/guide/creating-project and can't figure out the next steps. I am guessing that I will need multiple grammar files for the `build.php` step because namespaces don't seem to be supported (I get a parse error if I try to use the -> syntax above). So I tried to split up my existing grammar file into separate files for "default" and "sub", with their specific tokens defined in each, but then I'm not sure where to define the overall grammar. If I put everything in the "default" file I get an error because it refers to tokens that only exist in "sub".

Can you provide a simple example that shows how to achieve what I'm after? Thanks.

**Comment by SerafimArts** [comment]
Sorry for such a long delay. I didn't see the new issue in the notifications right away)))

I must admit... I don't remember, since this is a 5-year-old backward compatibility functionality. It is theoretically supported (including the grammar syntax), but it is not used much.

If I'm not mistaken, it's enough to simply indicate the transition between states and that's it, exactly as you wrote.
```php
echo (new \Phplrt\Compiler\Compiler())
    ->load(<<<'EBNF'
        %token open_brace {{ -> sub
        %token sub:close_brace }} -> default
        EBNF);

// Will generate

<?php

declare(strict_types=1);

/**
 * @var array{
 *     initial: array-key,
 *     tokens: array{
 *         default: array<non-empty-string, non-empty-string>,
 *         ...
 *     },
 *     skip: list<non-empty-string>,
 *     grammar: array<array-key, \Phplrt\Parser\Grammar\RuleInterface>,
 *     reducers: array<array-key, callable(\Phplrt\Parser\Context, mixed):mixed>,
 *     transitions?: array<array-key, mixed>
 * }
 */
return [
    'initial' => null,
    'tokens' => [
        'default' => [
            'open_brace' => '{{',
        ],
        'sub' => [
            'close_brace' => '}}',
        ],
    ],
    'skip' => [],
    'transitions' => [
        'default' => [
            'open_brace' => 'sub',
        ],
        'sub' => [
            'close_brace' => 'default',
        ],
    ],
    'grammar' => [],
    'reducers' => [],
];
```

This is already compiled grammar, which can be loaded into the parser and lexer as you need. Unlike Hoa, Phplrt does not generate source code, but only generates a grammar file (configs from which you can create objects as you like).

```php
// Like this

$grammar = __DIR__ . '/generated.php';

$lexer = new Multistate($grammar['transitions'], $grammar['tokens'], $grammar['initial']);
```

---

It would be nice to have a full grammar example, as maybe that's not the error. Phplrt doesn't support "capture names" for groups because they don't make sense, maybe that was the error?

```php
Some: (Any() Ololo() ::TOKEN:: #Name) // << Like this "#Name"
```

**Comment by pauljura** [comment]
Hey, thanks for the reply, but I moved on and forgot about this question :)

I don't even have my original code any more, so can't check anything.

I ended up using https://github.com/antlr/antlr-php-runtime
